Edit Group Chat
jcserv/ulinks pull request #12
Opened 2021-06-15 01:42 UTC by imphungky

## DEV-004

Fixes: #

- [X] Has the code been formatted?
- [ ] Have dependencies/packages been added/removed?
      If so, please list them.

### Changes

List out all the changes, and then explain the changes made at a higher level

- Modified chat/[id].jsx to contain the id and check user permissions for editting
- created a new form for editing containing current chat info
- modified query to fetch for more group chat information for editing

2021-06-24 02:00 UTC, jcserv requested changes
Great work, just a bit of feedback but after that I think it's good to go - pending a review from @AipioxTechson

2021-06-24 02:00 UTC, jcserv commented on client/content/locale/en.json
> +  "last-modified": "Last modified",
Could you also add these to fr.json?

2021-06-24 02:00 UTC, jcserv commented on client/pages/chat/[id].jsx
> +  const [editPermissions, setEditPermissions] = useState(false);
Nice! Do you think we could abstract this into something like a permission wrapper component?
I have no clue tbh I'm just wondering if we could apply this for other features

2021-06-24 02:00 UTC, jcserv commented on server/resolvers/GroupChatResolver.ts
> +import { courseInformationInput } from "../inputs/GroupChatInput";
unused

2021-06-24 02:00 UTC, jcserv commented on server/resolvers/GroupChatResolver.ts
> +  @Mutation(returns => Boolean)
I think you can change returns to () to remove the eslint warning

2021-06-24 02:00 UTC, jcserv commented on client/components/DeleteChatModal.jsx
> +    }
can we get a toast for when the delete is unsuccessful as well?

2021-06-24 02:00 UTC, jcserv commented on client/components/DeleteChatModal.jsx
> +            {formatMessage(messages.confirm)}
currently this content isn't populating for me

2021-06-24 02:11 UTC, AipioxTechson reviewed
Aside from Jerry's requested changes, it looks good!

2021-06-27 18:26 UTC, jcserv commented on client/components/DeleteChatModal.jsx
> +      });
Can you redirect the user to the homepage after deleting?

2021-06-27 18:50 UTC, merged