Feature/group metadata
jcserv/ulinks pull request #45
Opened 2021-07-17 18:20 UTC by CometWhoosh

## feat/group-metadata

Fixes: #3

- [x] Has the code been formatted?
- [ ] Have dependencies/packages been added/removed?
      If so, please list them.

### Changes

List out all the changes, and then explain the changes made at a higher level

* Added fields for views, likes, updated date, and created date to groupchats.
* Changed the Created and Last Modified dates on the chat info pages to use the metadata fields
* Made some UI changes:
  * Changed the layout of social media icons in cards to be horizontal
  * Made it so that the "ulinks" text in the navbar doesn't get underlined when hovered on
  * Made the social media buttons in the chat info pages have a tooltip of "Join the Discord server", "Join the WhatsApp group", or "Visit the Linktree page", depending on the icon
  * Added a tooltip for the globe icon in the navbar that says "Choose language"
  * Made the tabs under "Discover" get highlighted as black in light mode and as a lighter gray in dark mode
  * Changed the currently selected tab to have a background colour of blue in dark mode instead of green
  * Changed the page size to 9 so that the nine cards appear before the View More button

2021-07-17 19:44 UTC, AipioxTechson approved these changes

2021-07-17 20:00 UTC, jcserv requested changes
Great work! Very minor changes requested

2021-07-17 20:00 UTC, jcserv commented on client/components/ChatInfo.jsx
> +      label: "Join the WhatsApp group",
Can you intl-ize these labels?

2021-07-17 20:00 UTC, jcserv commented on client/components/NavBar.jsx
>        ulinks
did you wanna try ULinks like you suggested?

2021-07-18 12:00 UTC, jcserv approved these changes

2021-07-18 12:01 UTC, merged